name: wordpress_client
description: A library written purely in dart to interact with Wordpress REST API in a fluent manner. Supports Authorization as well.
version: 6.3.4
repository: https://github.com/ArunPrakashG/wordpress_client

environment:
  sdk: ">=2.18.0 <4.0.0"

dev_dependencies:
  temp_mail_gen: ^2.0.0
  path_provider: ^2.0.15
  test: ^1.24.3

dependencies:
  cookie_jar: ^4.0.2
  dio: ">=5.1.2 <6.0.0"
  dio_cookie_manager: ^3.0.0
  http_parser: ^4.0.2
  meta: ^1.9.1
  path: ^1.8.3
  synchronized: ^3.1.0
