name: wordpress_client
description: A library to interact with the Wordpress REST API. Supports most of the common endpoints and all of the CRUD operations on the endpoints.
version: 10.0.0
topics:
  - wordpress
  - parallel
  - crud
  - rest
homepage: https://github.com/ArunPrakashG/wordpress_client
repository: https://github.com/ArunPrakashG/wordpress_client
documentation: https://github.com/ArunPrakashG/wordpress_client/wiki
issue_tracker: https://github.com/ArunPrakashG/wordpress_client/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://www.buymeacoffee.com/arunprakashg

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  temp_mail_gen: ^2.0.0
  test: ^1.24.5
  faker: ^2.1.0
  personal_flutter_lints:
    git:
      url: https://github.com/ArunPrakashG/personal_flutter_lints.git
      ref: main

dependencies:
  collection: ^1.18.0
  dio: ^5.6.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  http_parser: ^4.0.2
  meta: ^1.12.0
  path: ^1.8.3
  web_socket_channel: ^2.4.2
